### ISSUE TITLE
Displaying a Contact's  photo uri 

### ISSUE THREAD

**Issue by oferDanon** [tamir7/Contacts#26]
Hey, 
I'm trying to display a contact's photoUri using UIL, and it's failing with the following FailReason:

java.lang.IllegalArgumentException:` URI: content://com.android.contacts/contacts/54971/photo/photo, calling user: <my package name>, calling package:<my package name>

Do you have any idea why this might happen?

If not, how would you suggest displaying photos retrieved from Contacts using contact.getPhotoUri()?

Thanks!

**Comment by ishaan1995** [comment]
**## For getting a Bitmap image, try MediaStore.Images.Media.getBitmap() as following :**

```
Query q = Contacts.getQuery();
List<Contact> contactList = q.find();
Contact current = contactList.get(i);
current.getPhotoUri();
Uri uri = Uri.parse(current.getPhotoUri());
Bitmap bitmap = MediaStore.Images.Media.getBitmap(this.getContentResolver(), uri);
```

**## else if using Picasso, try this**

```
Uri path = Uri.parse(current.getPhotoUri());
Picasso.with(mContext)
.load(path)
.into(mContactIv);
```  

**## Both work perfectly well! :+1:**

**Comment by tamir7** [comment]
Haven't worked with UIL in a long time. Both Picasso and Glide can show content URI's, and both code snipets from @ishaan1995  work. Reopen if you still have a problem.
