### ISSUE TITLE
Feature Request Get Birthdays of contacts

### ISSUE THREAD

**Issue by ghost** [tamir7/Contacts#3]
Hi, this library simplifies the task of getting the contacts on android devices.. can you extend it to obtain birthdates of these contacts?

**Comment by tamir7** [comment]
The issue reference is a mistake.

**Comment by tamir7** [comment]
Implemented. 2f74fb1e64f6d685c28b94364ae29038c1db1cc0 

Contact now has a getBirthday function.

**Comment by ghost** [comment]
Thanx :)
