### ISSUE TITLE
Find contact by id

### ISSUE THREAD

**Issue by ghost** [tamir7/Contacts#34]
Now that there is an id field visible within the Contact, do you intend on making the find contact by id a public query?

If not, how do you currently pass the Contact object to a new activity without it being a Parceable object? Do you just pass the display name to the new activity and then make query to find the Contact that way?

Thanks

**Comment by tamir7** [comment]
Made ContactID public. (ver 1.1.7)

I pass pojo's in my apps with Gson.

`String serializedContact = new Gson().toJson(contact);`
`Contact contact = new Gson().fromJson(serializedContact, Contact.class)`

**Comment by ghost** [comment]
Awesome! Thanks for merging my pull request and making those changes.

Since I'm dealing with thousands of contacts (approximately 6000) I still end up needing to use a find by ContactId query. If I include all of the fields I need upfront, the query takes a very long time. So instead, I used the serialized method suggested above, initially with a few fields, and then onClick to get all the remaining details of the contact that I need by doing that find by ContactId query.

Any recommendations for improvement? I've included my two separate queries below:
```
public List<Contact> getContactNamesNew() {
    Query q = Contacts.getQuery();
    q.hasPhoneNumber();
    q.include(
            Contact.Field.Address,
            Contact.Field.AddressType,
            Contact.Field.CompanyName,
            Contact.Field.DisplayName,
            Contact.Field.FamilyName,
            Contact.Field.GivenName,
            Contact.Field.ContactId,
            Contact.Field.Note,
            Contact.Field.PhotoUri
    );
    List<Contact> contacts = q.find();
    return contacts;
}

public Contact getContactById(Long id) {
    Query q = Contacts.getQuery();
    q.hasPhoneNumber();
    q.include(
            Contact.Field.Address,
            Contact.Field.AddressType,
            Contact.Field.CompanyName,
            Contact.Field.DisplayName,
            Contact.Field.Email,
            Contact.Field.EmailLabel,
            Contact.Field.FamilyName,
            Contact.Field.GivenName,
            Contact.Field.ContactId,
            Contact.Field.Note,
            Contact.Field.PhoneLabel,
            Contact.Field.PhoneNormalizedNumber,
            Contact.Field.PhoneNumber,
            Contact.Field.PhotoUri,
            Contact.Field.Website
    );
    q.whereEqualTo(Contact.Field.ContactId, id);
    List<Contact> contacts = q.find();
    if (!contacts.isEmpty()) {
        return contacts.get(0);
    } else {
        return null;
    }
}
```

**Comment by tamir7** [comment]
Do you actually need all of them at once? Or do you show them in a list in your app? In case of a list you can theoretically use pagination. It's theoretical cause I didn't implement it in the lib. :) But you can open another issue, and I'll add LIMIT and SKIP operators to the Query object when I have the time.

**Comment by ghost** [comment]
I do need all of the fields from the getContactNamesNew() initially because I am creating a list of the contacts in my app and separating them by certain characteristics of those fields, as well as providing search functionality based off of those fields.

Since it is a list, I think myself and others could certainly benefit from pagination :)

**Comment by tamir7** [comment]
I'm researching a way of doing that. Because I'm querying the ContactsContract.Data table, it's not as easy as adding limit and offset query params. Each Contact is returned in multiple rows.

**Comment by ghost** [comment]
Yeah it's certainly no easy feat. Since multiple rows are returned it makes it quite difficult to put a cap on the results because you don't know if all the rows for any particular contact have been seen yet.
