### ISSUE TITLE
MinSdk

### ISSUE THREAD

**Issue by TurhanOz** [tamir7/Contacts#6]
Hi, 

Is there any reason for the minApi 16 ?
Cheers

**Comment by tamir7** [comment]
Yes. I'm using NORMALIZED_NUMBER to query contacts instead of NUMBER. This field exists only from API 16. 

Check out:
https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Phone.html

**Comment by tamir7** [comment]
ver 1.1.0 min API version changed to 11.
